exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [flake8-docstrings, flake8-debugger, flake8-bugbear, mccabe]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        # Override default --ignore-missing-imports
        # Use pyproject.toml if possible instead of adding command line parameters here
        args: [ --warn-unused-configs ]
        additional_dependencies:
          # Type stubs
          - types-docutils
          - types-PyYAML
          - types-setuptools
          # Typed libraries
          - numpy
          - pytest

ci:
  # To trigger manually, comment on a pull request with "pre-commit.ci autofix"
  autofix_prs: false
  skip: []
