name: test-environment
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - distributed
  - Cython
  - sphinx
  - cartopy
  - pillow
  - pyyaml
  - pyproj
  - pyresample
  - coveralls
  - coverage
  - codecov
  - netcdf4
  - rasterio
  - rioxarray
  - zarr
  - pytest
  - pytest-cov
  - fsspec
  - pip
